version: "3.1"
services:
  springboot:
   image: veda1998/maven-web-app:TAG
   restart: always
   depends_on:
   - mongo
   ports:
   - 8080:8080
   networks:
   - springnetwork
   environment:
   - MONGO_DB_ROOT_HOSTNAME=mogo
   - MONGO_DB_ROOT_USERNAME=robinuttappa
   - MONGO_DB_ROOT_PASSWORD=8975758051r@
  mongo:
   image: mongo
   networks:
   - springnetwork
   volumes:
   - mongovol:/data/db
   environment:
   - MONGO_INITDB_ROOT_USERNAME=robinuttappa
   - MONGO_INITDB_ROOT_PASSWORD=8975758051r@
networks:
  springnetwork:
volumes:
 mongovol:
